apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: contentgc-prod
  namespace: default
spec:
  secretName: contentgc-tls
  issuerRef:
    name: letsencrypt
  commonName: content.gophercon.com
  dnsNames:
  - content.gophercon.com